version: "3"

services:
  gc-db:
    container_name: gc-db
    image: postgres:13-alpine
    ports:
      - ${POSTGRES_PORT}:${POSTGRES_PORT}
    command: postgres -p ${POSTGRES_PORT}
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    volumes:
      - /usr/local/gc-db-pg/data:/var/lib/postgresql/data
    networks:
      - gc-network

networks:
  gc-network:
    driver: bridge
